version: 2.1

jobs:
  backend:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd Backend_NodeJS && npm install
      - run:
          name: Run Tests
          command: cd Backend_NodeJS && npm run test

  frontend:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd frontend/revive-gallery-app && npm install
      - run:
          name: Run Tests
          command: cd frontend/revive-gallery-app && npm test
      - run:
          name: Create Build
          command: cd frontend/revive-gallery-app && CI='' npm run build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - backend:
          filters:
              branches:
                only: main # only deploy when on main
      - frontend:
          requires:
            - backend
          filters:
            branches:
              only: main # only deploy when on main



