@base_url = http://localhost:5000

# Test user registration with valid data
POST {{base_url}}/register
Content-Type: application/json

{
    "email": "janedoe@gmail.com",
    "first_name": "Jane",
    "last_name": "Doe",
    "password": "123456"
}

### create category
POST  {{base_url}}/categories/create
Content-Type: application/json

{
    "name": "Stationery"
}

###

# create a product
POST  {{base_url}}/products/create
Content-Type: application/json

{
    "name": "test product",

    "price": 100
}

###

GET {{base_url}}/products

